### ISSUE TITLE
[issue/bug]"Hardened Ice Shard" will not appear

### ISSUE THREAD

**Issue by Start-Buling** [aleganza/Plenty-Of-Armor#6]
Hello, 
    I found some issues while using your mod, the mod version is PlentyPlates-v8.0.0-1.20.1-Fabric and JEI is jei-1.20.1-fabric-15.2.0.25
    "Hardened Ice Shard" won't be visible in JEI, and it won't appear in the mod-specific item category within the creative mode menu. Nevertheless, crafting recipes for "Hardened Ice Shard" will still be viewable in JEI, and the item can be crafted as intended. However, when you hover your mouse over this item, the mod category won't be displayed.
![1@ 1A 8}S4@)EJ%4Q%)FBVJ](https://github.com/aleganza/Plenty-Of-Armors/assets/58358555/8093fae5-323b-4258-9df2-38d80cbcb461)

**Comment by aleganza** [comment]
Thank's for noticing! I think it's a little bug in the code, it will be surely fixed within the next update.

**Comment by Start-Buling** [comment]
It's a small favor. I look forward to your next update！

**Comment by aleganza** [comment]
Us too! 👀
