### ISSUE TITLE
We have the mod installed on a server with fabric in 1.20.1. Nothing in the mod appears to be craftable. We have jei installed and also jei shows no crafting recipe for any of the armor/intem

### ISSUE THREAD

**Issue by T3rr1X** [aleganza/Plenty-Of-Armor#9]

**Comment by aleganza** [comment]
very strange. Before publishing, I tested the mod in both local and server and it didn't give any problem, also it is in many modpacks and the craftings work ☹. I don't know what it could be, do other mods have the same problem or only Plenty Of Armors?

**Comment by T3rr1X** [comment]
actually i found similar problems with another mod later, so it's likely to
be a server side issue of bad interactions between mods :(

Il giorno mar 7 mag 2024 alle ore 00:13 Alessio Ganzarolli <
***@***.***> ha scritto:
